
export const ERRORS_SET = "ERRORS_SET"
export const ERRORS_RESET = "ERRORS_RESET"
export const ERRORS_SET_MIN_LENGTH = "ERRORS_SET_MIN_LENGTH"
export const ERRORS_SET_MAX_LENGTH = "ERRORS_SET_MAX_LENGTH"
export const ERRORS_SET_SHOULD_BE_HAVE_AN_UPPERCASE = "ERRORS_SET_SHOULD_BE_HAVE_AN_UPPERCASE"
export const ERRORS_SET_SHOULD_BE_HAVE_AN_NUMBER = "ERRORS_SET_SHOULD_BE_HAVE_AN_NUMBER"
export const ERRORS_SET_DONT_MATCH = "ERRORS_SET_DONT_MATCH"
